
// This file has been generated by the GUI designer. Do not modify.
namespace translinkupdater
{
	public partial class TitleList
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewTitles;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button button38;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget translinkupdater.TitleList
			this.Name = "translinkupdater.TitleList";
			this.Title = global::Mono.Unix.Catalog.GetString ("Välj sidtitlar");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child translinkupdater.TitleList.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>En sidtitel per rad</i>");
			this.label2.UseMarkup = true;
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewTitles = new global::Gtk.TextView ();
			this.textviewTitles.Buffer.Text = "\n";
			this.textviewTitles.CanFocus = true;
			this.textviewTitles.Name = "textviewTitles";
			this.GtkScrolledWindow.Add (this.textviewTitles);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button38 = new global::Gtk.Button ();
			this.button38.CanDefault = true;
			this.button38.CanFocus = true;
			this.button38.Name = "button38";
			this.button38.UseStock = true;
			this.button38.UseUnderline = true;
			this.button38.Label = "gtk-ok";
			this.hbox1.Add (this.button38);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button38]));
			w5.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.button38.HasDefault = true;
			this.Show ();
		}
	}
}
